name: 'Jest Code Coverage PR Comment'
description: 'create a PR comment of jest code coverage diff'
inputs:
  repo-token:
    description: 'GITHUB_TOKEN secret'
    required: true
  coverage-summary-path:
    description: 'optional coverage-summary.json path from jest'
  artifact-name:
    description: 'optional artifact name'
outputs:
  comment-url:
    description: 'The PR comment URL'
runs:
  using: 'node12'
  main: 'dist/index.js'
