on: [push]

jobs:
  job:
    runs-on: ubuntu-latest
    name: testing
    steps:
    - uses: actions/checkout@v2.0.0
    - uses: actions/setup-node@v1.4.0
      with:
        node-version: 12.x

    - name: first step
      id: first
      uses: ./
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get the output time
      run: echo "comment-url is ${{ steps.first.outputs.comment-url }}"
